### ISSUE TITLE
This or norm?

### ISSUE THREAD

**Issue by Beetroit** [PhilippMDoerner/TinyPool#5]
I am currently writing a web server in Happyx and would like to use an async database. I followed your discussion on norm's concurrency story, lowdb and now tinypool. What's your recommendation for high performance db implementation? I'll be using sqlite and pg. Thanks.

**Comment by PhilippMDoerner** [comment]
It's kind of an apple vs. oranges comparison. Tinypool just gives you DB connections, nothing more. Norm does all that (its own connection pool having been heavily inspired by this one) and also provides an ORM, so maps the SQL query results into models, abstracts CRUD and other simple operations while still having the same easy  access to write raw SQL.

Personally, if you're an application developer, there's really no reason to use this particular project over norm for the common webapplication where you want to make queries and have the results turned into nim-objects.
The savings in performance are potentially at most measured in the nano seconds, if there are any. And that is assuming you're writing a hyper-performant transformation function that beats norms own.

This library makes more sense to use as a library developer if you don't want to take care of this particular problem (How do I avoid having to instantiate a connection every time I want a request). Or back when norm didn't have its own connection pool, which has been added since.

Async you won't be getting either way in the current state that the libs are in. For norm to get it, it'd need to be first implemented in lowdb since norm uses that to abstract away direct db interactions.
That is rough though and I couldn't muster the passion for doing so.

**Comment by Beetroit** [comment]
I appreciate your prompt reply. Thanks, i'll just use norm then.
